apiVersion: secrets-store-gke.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cognira-bti-secret-provider
  namespace: cognira-bti
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/PROJECT_ID_PLACEHOLDER/secrets/cognira-bti-gcul-password/versions/latest"
        path: "gcul-password"
      - resourceName: "projects/PROJECT_ID_PLACEHOLDER/secrets/cognira-bti-ethereum-rpc-password/versions/latest"
        path: "ethereum-rpc-password"
      - resourceName: "projects/PROJECT_ID_PLACEHOLDER/secrets/cognira-bti-admin-password/versions/latest"
        path: "admin-password"
